fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Candydate\Entity\User
  service:
    mailer: fos_user.mailer.noop
  from_email:
    address: "noreply@candydate.local"
    sender_name: "No Reply"