nelmio_api_doc:
  documentation:
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
#    sandbox:
#        enabled: true
#        authentication:
#            delivery: http
#            type: bearer
#        body_format:
#            formats: [ json, form ]             # array of enabled body formats,
#            default_format: json
#    swagger:
#        api_base_path:        /api
#        swagger_version:      '1.2'
#        api_version:          '0.1'
#        info:
#            title:                Rest
#            description:          'Rest app in symfony 4'