#controllers:
#  resource: ../../src/Controller/
#  type: annotation

web_controller:
  resource: ../../src/Controller/Web/
  type: annotation
rest_controller:
  resource: ../../src/Controller/Rest/
  type: annotation
  prefix: /api
oauth_rest_controller:
  resource: ../../src/Controller/OAuth/
  type: annotation
  prefix: /client